# Generated by Django 4.2 on 2024-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatkaal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat_class',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', '3rd AC'), ('1A', '1st AC'), ('GEN', 'General'), ('2A', '2nd AC')], max_length=3),
        ),
    ]
